name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: WouterReusen/source-repo/.github/workflows/action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-repo: 'git@github.com:WouterReusen/source-repo.git'
        destination-repo: 'git@github.com:melexis-fir/destination-repo.git'
