name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: WouterReusen/mirroring_test/.github/workflows/action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source-repo: 'git@github.com:WouterReusen/mirroring_test.git'
        destination-repo: 'git@github.com:melexis-fir/wre_mirror_test.git'
